global:
  resolve_timeout: 5m

route:
  receiver: "default-webhook"
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  routes:
    - matchers:
        - severity="critical"
      receiver: "critical-webhook"
      continue: false
    - matchers:
        - severity="warning"
      receiver: "warning-webhook"
      continue: false

receivers:
  - name: "default-webhook"
    webhook_configs:
      - url: "http://webhook-sink:8080/post"
        send_resolved: true

  - name: "critical-webhook"
    webhook_configs:
      - url: "http://webhook-sink:8080/post?priority=2&canal=teams"
        send_resolved: true

  - name: "warning-webhook"
    webhook_configs:
      - url: "http://webhook-sink:8080/post?priority=0"
        send_resolved: true
