groups:
  - name: infra-basica
    rules:

      - alert: HostDown
        expr: up{job="node-exporter"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Host/exporter fora do ar ({{ $labels.instance }})"
          description: "O node-exporter não responde há 30s."

      - alert: EndpointDown
        expr: probe_success{job="blackbox-http"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Endpoint fora do ar ({{ $labels.instance }})"
          description: "O probe HTTP falhou para {{ $labels.instance }}."

      - alert: CPUAltaHost
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "CPU alta em {{ $labels.instance }}"
          description: "Uso de CPU acima de 80% nos últimos 2 minutos."

      - alert: MemoriaAltaHost
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Memória alta em {{ $labels.instance }}"
          description: "Uso de memória acima de 85%."

      - alert: DiscoCheio
        expr: (1 - (node_filesystem_avail_bytes{fstype!~"tmpfs|overlay"} / node_filesystem_size_bytes{fstype!~"tmpfs|overlay"})) * 100 > 85
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Disco quase cheio em {{ $labels.instance }} ({{ $labels.mountpoint }})"
          description: "Uso de disco acima de 85%."
